name: Build and Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # necesario para publicar en gh-pages

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies and build module
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install maturin pdoc
          maturin develop

      - name: Build HTML docs with pdoc
        run: |
          source venv/bin/activate
          pdoc html go3 --output-dir docs --force

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/go3