name: Build and Publish

on:
  push:
    branches:
      - "!*"  # No ramas
    tags:
      - "v*"  # Solo tags que empiecen por "v"

jobs:
  build:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install maturin
        run: pip install maturin

      - name: Build wheels and sdist
        id: build_package
        run: |
          maturin build --manifest-path go3/Cargo.toml --release --out dist
          maturin sdist --out dist
          echo "WHEELNAME=$(ls dist/*.whl)" >> $GITHUB_OUTPUT
          echo "TARNAME=$(ls dist/*.tar.gz)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .whl to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build_package.outputs.WHEELNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .tar.gz to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build_package.outputs.TARNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}